export const cartActionTypes = {
    TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    ADD_CART_ITEM_QUANTITY: 'ADD_CART_ITEM_QUANTITY',
    REMOVE_CART_ITEM_QUANTITY: 'REMOVE_CART_ITEM_QUANTITY',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM'
};